### ISSUE TITLE
Spree::ThemeSupport (NameError)

### ISSUE THREAD

**Issue by wandtasie** [romul/spree-solr-search#24]
I got the following error installing spree-solr-search the way its described in the readme file. Using the git repository fixes the problem.

``` bash
Requiring REXML
/home/matthias/.rvm/gems/ruby-1.9.3-p125/gems/spree_solr_search-0.40.3/lib/spree_solr_search_hooks.rb:1:in `<top (required)>': uninitialized constant Spree::ThemeSupport (NameError)
    from /home/matthias/.rvm/gems/ruby-1.9.3-p125/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
    from /home/matthias/.rvm/gems/ruby-1.9.3-p125/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
    from /home/matthias/.rvm/gems/ruby-1.9.3-p125/gems/spree_solr_search-0.40.3/lib/spree_solr_search.rb:2:in `<top (required)>'
    from /home/matthias/.rvm/gems/ruby-1.9.3-p125/gems/bundler-1.1.3/lib/bundler/runtime.rb:68:in `require'
    from /home/matthias/.rvm/gems/ruby-1.9.3-p125/gems/bundler-1.1.3/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
    from /home/matthias/.rvm/gems/ruby-1.9.3-p125/gems/bundler-1.1.3/lib/bundler/runtime.rb:66:in `each'
    from /home/matthias/.rvm/gems/ruby-1.9.3-p125/gems/bundler-1.1.3/lib/bundler/runtime.rb:66:in `block in require'
    from /home/matthias/.rvm/gems/ruby-1.9.3-p125/gems/bundler-1.1.3/lib/bundler/runtime.rb:55:in `each'
    from /home/matthias/.rvm/gems/ruby-1.9.3-p125/gems/bundler-1.1.3/lib/bundler/runtime.rb:55:in `require'
    from /home/matthias/.rvm/gems/ruby-1.9.3-p125/gems/bundler-1.1.3/lib/bundler.rb:119:in `require'
    from /home/matthias/public_html/spree_wandtasie/config/application.rb:7:in `<top (required)>'
    from /home/matthias/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.6/lib/rails/commands.rb:24:in `require'
    from /home/matthias/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.6/lib/rails/commands.rb:24:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by jumph4x** [comment]
Fixed README. Correct way is usually to use the :git source anyways.

Thanks.
