### ISSUE TITLE
Compatible with Spree 1.1?

### ISSUE THREAD

**Issue by malakada** [romul/spree-solr-search#31]
So I was trying to find a way to message you about this, but I couldn't find it. :/  Apologies, since I'm sure that this is the wrong place for this, but here goes.

You say it's compatible with spree master branch 1.0.  What do I need to do to get it to work with Spree 1.1?

Thanks. :)

**Comment by jumph4x** [comment]
Should be all set and good to go, considering Spree 1.1 only changed the way we change\navigate the #index collections by replacing meta_search w/ ransack. 

Give it a go, if you find problems, report back.

**Comment by malakada** [comment]
Oh fantastic!  (PHEW)  Thanks so much. :)

**Comment by malakada** [comment]
I've added the gems for acts_as_solr_reloaded and spree_solr_search, and I've got the solr server up and running on port 8982 (development).  I've also ran rails g spree_solr_search:install.  Running rake solr:reindex throws me a Timeout::Error, and the server says this:

Caused by: org.apache.lucene.queryParser.ParseException: Cannot parse 'type_s:Spree::Product': Encountered " ":" ": "" at line 1, column 14.
Was expecting one of:
    <EOF> 
    <AND> ...
    <OR> ...
    <NOT> ...
    "+" ...
    "-" ...
    "(" ...
    "*" ...
    "^" ...
    <QUOTED> ...
    <TERM> ...
    <FUZZY_SLOP> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...

```
at org.apache.lucene.queryParser.QueryParser.parse(QueryParser.java:177)
at org.apache.solr.search.QueryParsing.parseQuery(QueryParsing.java:74)
... 29 more
```

I've added "acts_as_solr" to my Product model.  I originally had what was recommended in the Spree docs, but simplified it to just that thinking it might help.

Not really sure where to go from here... if this is a 1.0/1.1 compatibility issue, or a my lack of doing ___ issue, or what.

**Comment by jumph4x** [comment]
It sounds like like you simply added the gem to your gemfile, whereas the README specifies you use the git source. Please copy paste the lines as shown.

If you already did that, show us your Gemfile.

**Comment by jumph4x** [comment]
Also if that has already been the case, you could try updating the acts_as_solr_reloaded gem w/ `bundle update acts_as_solr_reloaded`.

The bug you see who up was fixed in: https://github.com/dcrec1/acts_as_solr_reloaded/commit/8bddc73baea854106f53b35af173c3817062ba8a

**Comment by malakada** [comment]
Oh, sorry, I thought that was obvious that I had done that.  :)

It's already in there:

source 'https://rubygems.org'

gem 'rails', '~> 3.2.6'

gem 'mysql2' # For XOLogic Database

gem 'simple_form'
gem 'twitter-bootstrap-rails'
gem "spree", :git => "git://github.com/spree/spree.git", :branch => "1-1-stable"
gem 'spree_gateway', :git => 'git://github.com/spree/spree_gateway.git', :branch => "1-1-stable"
gem 'acts_as_solr_reloaded', :git => 'git://github.com/dcrec1/acts_as_solr_reloaded.git'
gem 'spree_solr_search', :git => 'git://github.com/romul/spree-solr-search.git'
#gem 'jetty-solr', :git => 'git://github.com/dcrec1/jetty-solr.git'
#gem 'delayed_job', '2.1.4'
gem "devise"
gem "thin"
gem 'aws-s3'
gem 'aws-sdk'

group :development, :test do
  gem 'sqlite3'
  gem 'rspec-rails'
  gem 'quiet_assets'
end

group :production do
  gem 'pg'
end

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platform => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

**Comment by jumph4x** [comment]
Paste the output for this:
`bundle show acts_as_solr_reloaded`

**Comment by malakada** [comment]
bundle show acts_as_solr_reloaded:

mel$ bundle show acts_as_solr_reloaded
/Users/mel/.rvm/gems/ruby-1.9.2-p318/bundler/gems/acts_as_solr_reloaded-2ca97ff03ede

I did run the bundle update acts_as_solr_reloaded and there is no change in behaviour.

**Comment by jumph4x** [comment]
That is the correct version of acts_as_solr_reloaded. Really bizarre. I am assuming you're running your rake tasks through bundler, right? 

`bundle exec rake solr:reindex`
versus
`rake solr:reindex`

**Comment by malakada** [comment]
Nooo... I'm not, but when I run it through bundle exec rake solr:reindex I still get the same error. :S

I don't really know enough about Solr and how it works to even know how to begin to attempt to troubleshoot fixing this.  Any ideas?

**Comment by malakada** [comment]
Swapped to Ruby 1.9.3 and it's the same error... (I'm on 1.9.2 so I can use db:push up to Heroku... otherwise gives a weird taps timestamp error.)  so it's not the version of Ruby. :/

**Comment by jumph4x** [comment]
Change Gemfile to this (taken from a tested working Spree 1.1.X app): 

```
gem 'acts_as_solr_reloaded', :git => 'git://github.com/jumph4x/acts_as_solr_reloaded.git'
```

**Comment by malakada** [comment]
Great success!  Hahaha.  Wonderful!

Now to integrate into Spree.... thanks so much for your attention here. :)

**Comment by jumph4x** [comment]
Looks like they reverted the fix in one of many commits that came through. TODO, open issue + pull request on the canonical acts_as_solr_reloaded repo.

**Comment by malakada** [comment]
TODO on my pile or your pile? :P

**Comment by jumph4x** [comment]
I know what needs to be done, I'll take care of it.

**Comment by malakada** [comment]
Many thanks. :)

**Comment by jumph4x** [comment]
Issue filed in the canonical repo: https://github.com/dcrec1/acts_as_solr_reloaded/issues/27

**Comment by jumph4x** [comment]
Pull request sent: https://github.com/dcrec1/acts_as_solr_reloaded/pull/28
