### ISSUE TITLE
spree_solr_search breaks rake db:migrate

### ISSUE THREAD

**Issue by vandrijevik** [romul/spree-solr-search#7]
After adding spree_solr_search to a spree project (spree version "0.50.99"), `rake db:migrate` on an empty database does not work:

```
$ RAILS_ENV=production rake db:migrate --trace
Requiring REXML
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
Table 'rails_application_production.products' doesn't exist
/ruby/default/gems/gems/mysql2-0.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:312:in `query'
/ruby/default/gems/gems/mysql2-0.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:312:in `execute'
/ruby/default/gems/gems/mysql2-0.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:462:in `columns'
/ruby/default/gems/gems/activerecord-3.0.4/lib/active_record/base.rb:679:in `columns'
/ruby/default/gems/gems/activerecord-3.0.4/lib/active_record/base.rb:687:in `columns_hash'
/ruby/default/gems/gems/acts_as_solr_reloaded-1.5.0/lib/acts_as_solr/acts_methods.rb:351:in `type_for_field'
/ruby/default/gems/gems/acts_as_solr_reloaded-1.5.0/lib/acts_as_solr/acts_methods.rb:344:in `determine_field_name_and_options'
/ruby/default/gems/gems/acts_as_solr_reloaded-1.5.0/lib/acts_as_solr/acts_methods.rb:296:in `get_field_value'
/ruby/default/gems/gems/acts_as_solr_reloaded-1.5.0/lib/acts_as_solr/acts_methods.rb:320:in `process_fields'
/ruby/default/gems/gems/acts_as_solr_reloaded-1.5.0/lib/acts_as_solr/acts_methods.rb:318:in `each'
/ruby/default/gems/gems/acts_as_solr_reloaded-1.5.0/lib/acts_as_solr/acts_methods.rb:318:in `process_fields'
/ruby/default/gems/gems/acts_as_solr_reloaded-1.5.0/lib/acts_as_solr/acts_methods.rb:282:in `process_solr_options'
/ruby/default/gems/gems/acts_as_solr_reloaded-1.5.0/lib/acts_as_solr/acts_methods.rb:190:in `process_acts_as_solr'
/ruby/default/gems/gems/acts_as_solr_reloaded-1.5.0/lib/acts_as_solr/acts_methods.rb:185:in `acts_as_solr'
/ruby/default/gems/gems/spree_solr_search-0.40.0/lib/../app/models/product_decorator.rb:6
/ruby/default/gems/gems/spree_solr_search-0.40.0/lib/../app/models/product_decorator.rb:1:in `class_eval'
/ruby/default/gems/gems/spree_solr_search-0.40.0/lib/../app/models/product_decorator.rb:1
/ruby/default/gems/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in `require'
/ruby/default/gems/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in `require'
/ruby/default/gems/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:227:in `load_dependency'
/ruby/default/gems/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in `require'
/ruby/default/gems/gems/spree_solr_search-0.40.0/lib/spree_solr_search.rb:17:in `activate'
/ruby/default/gems/gems/spree_solr_search-0.40.0/lib/spree_solr_search.rb:16:in `glob'
/ruby/default/gems/gems/spree_solr_search-0.40.0/lib/spree_solr_search.rb:16:in `activate'
/ruby/default/gems/gems/spree_solr_search-0.40.0/lib/spree_solr_search.rb:6:in `_callback_before_51'
/ruby/default/gems/gems/activesupport-3.0.4/lib/active_support/callbacks.rb:439:in `_run_prepare_callbacks'
/ruby/default/gems/gems/actionpack-3.0.4/lib/action_dispatch/middleware/callbacks.rb:40:in `initialize'
/ruby/default/gems/gems/actionpack-3.0.4/lib/action_dispatch/middleware/stack.rb:33:in `new'
/ruby/default/gems/gems/actionpack-3.0.4/lib/action_dispatch/middleware/stack.rb:33:in `build'
/ruby/default/gems/gems/actionpack-3.0.4/lib/action_dispatch/middleware/stack.rb:79:in `build'
/ruby/default/gems/gems/railties-3.0.4/lib/rails/application.rb:208:in `inject'
/ruby/default/gems/gems/actionpack-3.0.4/lib/action_dispatch/middleware/stack.rb:79:in `each'
/ruby/default/gems/gems/actionpack-3.0.4/lib/action_dispatch/middleware/stack.rb:79:in `inject'
/ruby/default/gems/gems/actionpack-3.0.4/lib/action_dispatch/middleware/stack.rb:79:in `build'
/ruby/default/gems/gems/railties-3.0.4/lib/rails/application.rb:162:in `build_middleware_stack'
/ruby/default/gems/gems/railties-3.0.4/lib/rails/application/finisher.rb:35
/ruby/default/gems/gems/railties-3.0.4/lib/rails/initializable.rb:25:in `instance_exec'
/ruby/default/gems/gems/railties-3.0.4/lib/rails/initializable.rb:25:in `run'
/ruby/default/gems/gems/railties-3.0.4/lib/rails/initializable.rb:50:in `run_initializers'
/ruby/default/gems/gems/railties-3.0.4/lib/rails/initializable.rb:49:in `each'
/ruby/default/gems/gems/railties-3.0.4/lib/rails/initializable.rb:49:in `run_initializers'
/ruby/default/gems/gems/railties-3.0.4/lib/rails/application.rb:134:in `initialize!'
/ruby/default/gems/gems/railties-3.0.4/lib/rails/application.rb:77:in `send'
/ruby/default/gems/gems/railties-3.0.4/lib/rails/application.rb:77:in `method_missing'
```

This makes it impossible to set up a new instance of the app (using the instructions at https://github.com/spree/spree/blob/master/README.md) after spree_solr_search is added.

**Comment by romul** [comment]
You should at first install Spree and only after this install extensions. If Spree installed, then products table exists!!!

**Comment by vandrijevik** [comment]
Romul, that is what happened in this case. However, after adding spree_solr_search, I want to deploy the application on an additional server.

When I attempt to do so, I get the above error.

**Comment by tonycoco** [comment]
You can get around this by simply deploying without the spree-solr-search gem in your Gemfile/Gemfile.lock and then adding it back and redeploying. But yeah, this is for sure a bug. I'll look at it and try to put in a fix.

**Comment by romul** [comment]
This https://github.com/romul/spree-solr-search/commit/2ab47174313ca90f91e7e687dc02a1bfed57a036 should help

**Comment by denislutz** [comment]
Hey Roman I am still having this issue again, setup works one after each other, if I want to do it on one shot, the migrate doesnt work, spree solr prevents it. Any idea how to fix it?
Here is my sample project:  https://github.com/denislutz/spree_proc

just clone it and try to migrate.

Thx a lot,

Denis.
